-- Default categories and rules. Rules reference categories by name so the
-- seed does not depend on generated ids. "contains"/"equals"/"prefix"
-- comparisons are case-insensitive in the application.

INSERT INTO categories (name, color, is_transfer, sort_order, created_at) VALUES
    ('Продукты',           '#2e7d32', FALSE, 10,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Кафе и рестораны',   '#ef6c00', FALSE, 20,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Доставка еды',       '#f9a825', FALSE, 30,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Такси',              '#1565c0', FALSE, 40,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Транспорт',          '#0277bd', FALSE, 50,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Спорт',              '#6a1b9a', FALSE, 60,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Здоровье и аптеки',  '#c62828', FALSE, 70,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Связь и интернет',   '#00838f', FALSE, 80,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Подписки и сервисы', '#5e35b1', FALSE, 90,  TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Развлечения',        '#ad1457', FALSE, 100, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Электроника',        '#37474f', FALSE, 110, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Одежда',             '#8d6e63', FALSE, 120, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Дом',                '#558b2f', FALSE, 130, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Прочее',             '#9e9e9e', FALSE, 900, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Переводы',           '#78909c', TRUE,  910, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Пополнения',         '#43a047', TRUE,  920, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Кэшбэк',             '#7cb342', FALSE, 930, TIMESTAMPTZ '2026-09-12 00:00:00+00'),
    ('Возвраты',           '#9e9d24', FALSE, 940, TIMESTAMPTZ '2026-09-12 00:00:00+00')
ON CONFLICT (name) DO NOTHING;

INSERT INTO category_rules (category_id, field, op, value, priority, created_at)
SELECT c.id, r.field, r.op, r.value, r.priority, TIMESTAMPTZ '2026-09-12 00:00:00+00'
FROM (VALUES
    ('Пополнения',         'kind',     'equals',   'transfer_in',      5),
    ('Переводы',           'kind',     'equals',   'transfer_out',     5),
    ('Кэшбэк',             'kind',     'equals',   'cashback',         5),
    ('Возвраты',           'kind',     'equals',   'refund',           5),
    ('Доставка еды',       'merchant', 'contains', 'EDA',              10),
    ('Такси',              'merchant', 'contains', 'TAXI',             10),
    ('Продукты',           'merchant', 'contains', 'SAMOKAT',          10),
    ('Такси',              'mcc',      'equals',   '4121',             20),
    ('Продукты',           'mcc',      'equals',   '5411',             20),
    ('Продукты',           'merchant', 'contains', 'MARIYA-RA',        30),
    ('Продукты',           'merchant', 'contains', 'Мария-Ра',         30),
    ('Продукты',           'merchant', 'contains', 'MAGNIT',           30),
    ('Продукты',           'merchant', 'contains', 'Магнит',           30),
    ('Продукты',           'merchant', 'contains', 'YARCHE',           30),
    ('Продукты',           'merchant', 'contains', 'MONETKA',          30),
    ('Продукты',           'merchant', 'contains', 'BAHETLE',          30),
    ('Продукты',           'merchant', 'contains', 'GASTRONOM',        30),
    ('Продукты',           'merchant', 'contains', 'Гастроном',        30),
    ('Спорт',              'merchant', 'contains', 'Metrofitnes',      30),
    ('Спорт',              'merchant', 'contains', 'Метрофитнес',      30),
    ('Кафе и рестораны',   'merchant', 'contains', 'Додо',             30),
    ('Кафе и рестораны',   'merchant', 'contains', 'Tangiers',         30),
    ('Кафе и рестораны',   'merchant', 'contains', 'COFFEE',           30),
    ('Кафе и рестораны',   'merchant', 'contains', 'Кофе',             30),
    ('Кафе и рестораны',   'merchant', 'contains', 'KOFE',             30),
    ('Кафе и рестораны',   'merchant', 'contains', 'KAFE',             30),
    ('Кафе и рестораны',   'merchant', 'contains', 'Croque',           30),
    ('Кафе и рестораны',   'merchant', 'contains', 'Шаурма',           30),
    ('Кафе и рестораны',   'merchant', 'contains', 'SHAMPUR',          30),
    ('Кафе и рестораны',   'merchant', 'contains', 'NETMONET',         30),
    ('Кафе и рестораны',   'merchant', 'contains', 'Праймтайм',        30),
    ('Связь и интернет',   'merchant', 'contains', 'TRAFFIC',          30),
    ('Связь и интернет',   'merchant', 'contains', 'ЭР-ТЕЛЕКОМ',       30),
    ('Здоровье и аптеки',  'merchant', 'contains', 'APTE',             30),
    ('Здоровье и аптеки',  'merchant', 'contains', 'FARM',             30),
    ('Здоровье и аптеки',  'merchant', 'contains', 'Аптека',           30),
    ('Электроника',        'merchant', 'contains', 'DNS-SHOP',         30),
    ('Развлечения',        'merchant', 'contains', 'IGROMAGAZ',        30),
    ('Развлечения',        'merchant', 'contains', 'Хука',             30),
    ('Подписки и сервисы', 'merchant', 'contains', 'Сервисы Яндекса',  30),
    ('Подписки и сервисы', 'merchant', 'contains', 'PLUS',             30),
    ('Кафе и рестораны',   'mcc',      'equals',   '5812',             40),
    ('Кафе и рестораны',   'mcc',      'equals',   '5813',             40),
    ('Кафе и рестораны',   'mcc',      'equals',   '5814',             40),
    ('Здоровье и аптеки',  'mcc',      'equals',   '5912',             40),
    ('Подписки и сервисы', 'mcc',      'equals',   '5815',             40),
    ('Транспорт',          'mcc',      'equals',   '4111',             40),
    ('Транспорт',          'mcc',      'equals',   '5541',             40),
    ('Одежда',             'mcc',      'equals',   '5651',             40),
    ('Одежда',             'mcc',      'equals',   '5691',             40)
) AS r (category, field, op, value, priority)
JOIN categories c ON c.name = r.category;
